services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dreams-cup-api
    container_name: postgres
    ports:
      - '5499:5432'
